services:
  service:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - 'MICRONAUT_ENVIRONMENTS=local'
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'